### ISSUE TITLE
Application crashing

### ISSUE THREAD

**Issue by andrew01ait** [timothyb89/lifx-tasker#3]
First of all, thanks for this plugin! I've been looking for something like this since I've received my bulbs! Yesterday I've tried running the alpha 1.0 version on my HTC One X (Android 4.2.2) but the application crashed when trying to launch it or when hitting the 'edit' button when selecting bulbs in Tasker.

Please find attached the relevant parts of my logcat output.

05-23 12:21:31.405: I/ActivityManager(503): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.timothyb89.lifx.tasker/.SimpleControlActivity_} from pid 877
05-23 12:21:31.420: I/Intent(503): @test_code: getHtcIntentFlag: 0 obj: 1113087648
05-23 12:21:31.430: D/PowerManagerService(503): acquireWakeLock(420bc158): PARTIAL_WAKE_LOCK , tag=ActivityManager-Launch, flags=0x1, pid=503, uid=1000
05-23 12:21:31.480: I/FeedHostManager(877): onPause
05-23 12:21:31.480: I/FeedProviderManager(877): onPause
05-23 12:21:31.480: I/SocialFeedProvider(877): +onPause
05-23 12:21:31.480: I/SocialFeedProvider(877): -onPause
05-23 12:21:31.500: D/CAT(964): CatService: Return current sInstance
05-23 12:21:31.515: I/ActivityManager(503): Start proc org.timothyb89.lifx.tasker for activity org.timothyb89.lifx.tasker/.SimpleControlActivity_: pid=25620 uid=10192 gids={50192, 3003, 5012, 1028}
05-23 12:21:31.915: D/WirelessDisplayService(503): getMirrorDisplayStatus:falsecurState:1
05-23 12:21:31.935: I/TrimMemoryManager(877): trimMemory(20)
05-23 12:21:31.945: I/Launcher(877): updateWallpaperVisibility: true
05-23 12:21:31.960: W/ResourceType(503): Skipping entry 0x7f040006 in package table 0 because it is not complex!
05-23 12:21:31.965: W/ResourceType(503): Skipping entry 0x7f040004 in package table 0 because it is not complex!
05-23 12:21:32.055: I/q(936): :a3: Phone unlocked without subject showing
05-23 12:21:32.170: I/q(936): :a3: Phone unlocked without subject showing
05-23 12:21:32.255: I/q(936): :a3: Phone unlocked without subject showing
05-23 12:21:32.260: I/SimpleControlActivity(25620): Starting service
05-23 12:21:32.420: I/o_.t_.l_.t_.LIFXService(25620): LIFX service started
05-23 12:21:32.425: W/dalvikvm(25620): VFY: unable to resolve static method 1202: Ljava/util/Objects;.hashCode (Ljava/lang/Object;)I
05-23 12:21:32.430: W/dalvikvm(25620): VFY: unable to resolve exception class 302 (Ljava/lang/ReflectiveOperationException;)
05-23 12:21:32.430: W/dalvikvm(25620): VFY: unable to find exception handler at addr 0x40
05-23 12:21:32.430: W/dalvikvm(25620): VFY:  rejected Lorg/timothyb89/lifx/net/android/WifiManagerProxy;.getInstance (Ljava/lang/Object;)Lorg/timothyb89/lifx/net/android/WifiManagerProxy;
05-23 12:21:32.430: W/dalvikvm(25620): VFY:  rejecting opcode 0x0d at 0x0040
05-23 12:21:32.435: W/dalvikvm(25620): VFY:  rejected Lorg/timothyb89/lifx/net/android/WifiManagerProxy;.getInstance (Ljava/lang/Object;)Lorg/timothyb89/lifx/net/android/WifiManagerProxy;
05-23 12:21:32.435: W/dalvikvm(25620): Verifier rejected class Lorg/timothyb89/lifx/net/android/WifiManagerProxy;
05-23 12:21:32.435: W/dalvikvm(25620): threadid=12: thread exiting with uncaught exception (group=0x40e75a08)
05-23 12:21:32.440: D/WakeLockManager(877): releaseWakeLock(com.htc.launcher.Launcher@412d18a8) tag=PrismLaunchActivity_4
05-23 12:21:32.440: E/AndroidRuntime(25620): FATAL EXCEPTION: lifx-udp-broadcast
05-23 12:21:32.440: E/AndroidRuntime(25620): java.lang.VerifyError: org/timothyb89/lifx/net/android/WifiManagerProxy
05-23 12:21:32.440: E/AndroidRuntime(25620):    at org.timothyb89.lifx.net.BroadcastListener$3.run(BroadcastListener.java:196)
05-23 12:21:32.440: E/AndroidRuntime(25620):    at java.lang.Thread.run(Thread.java:864)
05-23 12:21:32.440: D/PowerManagerService(503): releaseHtcCpuCtrl(425861e0): CPU_MIN_NUM, tag=PrismLaunchActivity_4, flags=0x400
05-23 12:21:32.440: D/PowerManagerService(503): releaseHtcCpuCtrl(42565708): CPU_MIN_FREQ, tag=PrismLaunchActivity_4, flags=0x100
05-23 12:21:32.445: E/EmbeddedLogger(503): App crashed! Process: org.timothyb89.lifx.tasker
05-23 12:21:32.445: E/EmbeddedLogger(503): App crashed! Package: org.timothyb89.lifx.tasker v1 (1.0-SNAPSHOT)
05-23 12:21:32.445: E/EmbeddedLogger(503): Application Label: LIFX Tasker Plugin
05-23 12:21:32.480: W/ActivityManager(503):   Force finishing activity org.timothyb89.lifx.tasker/.SimpleControlActivity_

Thanks
kr Andrew

**Comment by timothyb89** [comment]
Hello,

My apologies for the delay in responding. Unfortunately the app requires Android 4.4 to run, but the first version posted to the play store was incorrectly flagged as supporting Android 2.3+. I'll be looking into back-porting the app to run on older versions when I have some free time, but it takes advantage of a bunch of 4.4+ features so it might be difficult.

Sorry for the trouble!
